server:
  port: 31200
spring:
  application:
    name: edu-service-manage-course
  datasource:
    username: root
    password: 123
    url: jdbc:mysql:///xc_course?characterEncoding=utf-8
mybatis:
  mapper-locations: classpath:mappers/*.xml
pagehelper:
  helper-dialect: mysql
logging:
  level.wang.ismy.edu.manage_course.dao: debug