server:
  port: 31200
spring:
  application:
    name: edu-service-manage-course
  datasource:
    username: root
    password: 123
    url: jdbc:mysql:///xc_course
mybatis:
  mapper-locations: classpath:mappers/*.xml