server:
  port: 31200
spring:
  application:
    name: service-manage-course
  datasource:
    username: root
    password: 123
    url: jdbc:mysql:///xc_course?characterEncoding=utf-8
mybatis:
  mapper-locations: classpath:mappers/*.xml
pagehelper:
  helper-dialect: mysql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:50101/eureka/

ribbon:
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: false
  ConnectTimeout: 5000
  ReadTimeout: 6000