server:
  port: 31001
spring:
  application:
    name: edu-service-manage-cms
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
  rabbitmq:
    virtual-host: /
    host: my-pc
  data:
    mongodb:
      database: edu_cms
      uri: mongodb://localhost
