server:
  port: ${PORT:31001}
spring:
  application:
    name: service-manage-cms
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
  rabbitmq:
    virtual-host: /
    host: my-pc
  data:
    mongodb:
      database: edu_cms
      uri: mongodb://localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:50101/eureka/
